// Code generated by gormer. DO NOT EDIT.
package model

import (
	"context"

	"github.com/Junedayday/micro_web_service/internal/gormer"
)

type OrderModel interface {
	AddOrder(ctx context.Context, order *gormer.Order) (err error)
	QueryOrders(ctx context.Context, pageNumber, pageSize int, condition *gormer.OrderOptions) (orders []gormer.Order, err error)
	CountOrders(ctx context.Context, condition *gormer.OrderOptions) (count int64, err error)
	UpdateOrder(ctx context.Context, updated, condition *gormer.OrderOptions) (err error)
	DeleteOrder(ctx context.Context, condition *gormer.OrderOptions) (err error)

	// Implement Your Method in ext model
	OrderExtModel
}
