// Code generated by gormer. DO NOT EDIT.
package dao

import (
	"context"
	"time"
	
	"github.com/pkg/errors"
	"gorm.io/gorm"
	
	"github.com/Junedayday/micro_web_service/internal/gormer"
	"github.com/Junedayday/micro_web_service/internal/model"
)

type OrderRepo struct {
	db *gorm.DB
}

func NewOrderRepo(db *gorm.DB) *OrderRepo {
	return &OrderRepo{db: db}
}

var _ model.OrderModel = NewOrderRepo(nil)

func (repo *OrderRepo) AddOrder(ctx context.Context, order *gormer.Order) (err error) {

    if order.CreateTime.IsZero() {
		order.CreateTime = time.Now()
	}


    if order.UpdateTime.IsZero() {
		order.UpdateTime = time.Now()
	}

	repo.db.
		Table(gormer.OrderTableName).
		Create(order)
	err = getError(ctx, repo.db)
	return
}

func (repo *OrderRepo) QueryOrders(ctx context.Context, pageNumber, pageSize int, condition *gormer.OrderOptions) (orders []gormer.Order, err error) {
	db := repo.db
	if condition != nil {
		db = db.Where(condition.Order, condition.Fields)
	}

	db = db.Where("delete_status != ?", 1)

	db.
		Table(gormer.OrderTableName).
		Limit(pageSize).
		Offset((pageNumber - 1) * pageSize).
		Find(&orders)
	err = getError(ctx, repo.db)
	return
}

func (repo *OrderRepo) CountOrders(ctx context.Context, condition *gormer.OrderOptions) (count int64, err error) {
	db := repo.db
	if condition != nil {
		db = db.Where(condition.Order, condition.Fields)
	}

	db = db.Where("delete_status != ?", 1)

	db.
		Table(gormer.OrderTableName).
		Count(&count)
	err = getError(ctx, repo.db)
	return
}

func (repo *OrderRepo) UpdateOrder(ctx context.Context, updated, condition *gormer.OrderOptions) (err error) {
	if updated == nil || len(updated.Fields) == 0 {
		return errors.New("update must choose certain fields")
	} else if condition == nil {
		return errors.New("update must include where condition")
	}

    if updated.Order.UpdateTime.IsZero() {
		updated.Order.UpdateTime = time.Now()
		updated.Fields = append(updated.Fields, "update_time")
	}

	repo.db.
		Table(gormer.OrderTableName).
		Where(condition.Order, condition.Fields).
		Select(updated.Fields).
		Updates(updated.Order)
	err = getError(ctx, repo.db)
	return
}

func (repo *OrderRepo) DeleteOrder(ctx context.Context, condition *gormer.OrderOptions) (err error) {
	if condition == nil {
		return errors.New("delete must include where condition")
	}

	repo.db.
        Table(gormer.OrderTableName).
		Where(condition.Order, condition.Fields).
  
                Select("delete_status","update_time").
				Updates(&gormer.Order{
					DeleteStatus:1,
					UpdateTime : time.Now(),
				})
            

	err = getError(ctx, repo.db)
	return
}

