package main

const (
	modelHeader = `// Code generated by gormer. DO NOT EDIT.
package %s

import (
	"context"
	
	"%s/%s"
)
`

	modelExtHeader = `package %s

// write you method here
`
)

var (
	modelTmpl = `
type {{.StructName}}Model interface {
	Add{{.StructName}}(ctx context.Context, {{.StructSmallCamelName}} *gormer.{{.StructName}}) (err error)
	Query{{.StructName}}s(ctx context.Context, pageNumber, pageSize int, condition *gormer.{{.StructName}}Options) ({{.StructSmallCamelName}}s []gormer.{{.StructName}}, err error)
	Count{{.StructName}}s(ctx context.Context, condition *gormer.{{.StructName}}Options) (count int64, err error)
	Update{{.StructName}}(ctx context.Context, updated, condition *gormer.{{.StructName}}Options) (err error)
	Delete{{.StructName}}(ctx context.Context, condition *gormer.{{.StructName}}Options) (err error)
	
	// Implement Your Method in ext model
	{{.StructName}}ExtModel
}
`
	modelExtTmpl = `
type %sExtModel interface {
}
`
)
